# -*- coding: utf-8 -*-
"""predicted prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzdD-2965Si3uAd19dBYEWM8UScFrGtg
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

train_df = pd.read_csv('/content/train.csv')
test_df = pd.read_csv('/content/test.csv')

train_df.info()

# Feature Engineering: Encode categorical features and standardize numerical features
categorical_features = ['brand', 'model', 'fuel_type', 'transmission', 'ext_col', 'int_col','engine','accident','clean_title']
encoder = LabelEncoder()

for feature in categorical_features:
    train_df[feature] = encoder.fit_transform(train_df[feature])

# Standardize numerical features
scaler = StandardScaler()
numerical_features = ['id', 'model_year', 'milage','price']
train_df[numerical_features] = scaler.fit_transform(train_df[numerical_features])

# Splitting the Data
X = train_df.drop(['price', 'id'], axis=1)
y = train_df['price']
vehicle_ids = train_df['id']

# Split the data
X_train, X_test, y_train, y_test, ids_train, ids_test = train_test_split(X, y, vehicle_ids, test_size=0.2, random_state=42)

# Model Selection and Training: Using Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Model Evaluation
y_pred = rf_model.predict(X_test)
print('Random Forest:')
print('MAE:', mean_absolute_error(y_test, y_pred))
print('MSE:', mean_squared_error(y_test, y_pred))
print('R-squared:', r2_score(y_test, y_pred))

# Saving Predictions to CSV
# Create a DataFrame with IDs and predicted prices
predictions_df = pd.DataFrame({
    'ID': ids_test,
    'Actual Price': y_test,
    'Predicted Price': y_pred
})

# Save the DataFrame to a CSV file
predictions_df.to_csv('predicted_prices_with_id.csv', index=False)

print("Predictions have been saved to 'predicted_prices_with_id.csv'")